# Generated by Django 3.1.1 on 2020-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20201003_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.FilePathField(path='/home/herman/Desktop/hermanApp/img'),
        ),
    ]
