# Generated by Django 3.1.1 on 2020-10-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20201003_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
